<?php

namespace AppBundle\Repository;

/**
 * HasilRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HasilRepository extends \Doctrine\ORM\EntityRepository
{
}
