<?php

namespace AppBundle\Repository;

/**
 * LaboratoriumRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LaboratoriumRepository extends \Doctrine\ORM\EntityRepository
{
}
