<?php

namespace AppBundle\Repository;

/**
 * PelangganRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PelangganRepository extends \Doctrine\ORM\EntityRepository
{
}
