<?php

namespace AppBundle\Repository;

/**
 * SampelRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SampelRepository extends \Doctrine\ORM\EntityRepository
{
}
