# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        AppBundle\Entity\User:
            algorithm: md5
            encode_as_base64: false
            iterations: 0

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory: ~
        medical_db:
            entity:
                class: AppBundle:User
                property: username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            provider: medical_db
            form_login:
                login_path: medical_auth_login
                check_path: medical_auth_login
            logout:
                path: /auth/logout
                target: /

    access_control:
        - { path: ^/auth/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user, roles: ROLE_ADMIN }
        - { path: ^/transaksi, roles: [ROLE_PELAYANAN, ROLE_ADMIN] }
        - { path: ^/pelanggan, roles: [ROLE_PELAYANAN, ROLE_ADMIN] }
        - { path: ^/sampel, roles: [ROLE_PELAYANAN, ROLE_ANALIS, ROLE_ADMIN]}
        - { path: ^/hasil/list, roles: [ROLE_PELAYANAN, ROLE_MANAJER, ROLE_ADMIN] }
        - { path: ^/hasil/pending, roles: [ROLE_PELAYANAN, ROLE_MANAJER, ROLE_ADMIN] }
        - { path: ^/hasil/approved, roles: [ROLE_PELAYANAN, ROLE_MANAJER, ROLE_ANALIS, ROLE_ADMIN]}
        - { path: ^/hasil/refusal, roles: [ROLE_PELAYANAN, ROLE_MANAJER, ROLE_ANALIS, ROLE_ADMIN]}
        - { path: ^/lab, roles: [ROLE_ANALIS, ROLE_ADMIN]}
        - { path: ^/stp, roles: [ROLE_MANAJER, ROLE_ADMIN]}
        - { path: ^/, roles: [ROLE_ADMIN, ROLE_MANAJER, ROLE_ANALIS, ROLE_PELAYANAN] }

