medical_index:
  path: /
  defaults:
    _controller: AppBundle:Defaults/DefaultsHomepage:index

medical_user:
  resource: 'user/routing.yml'
  prefix: /user

medical_auth:
  resource: 'auth/routing.yml'
  prefix: /auth

medical_lab:
  resource: 'lab/routing.yml'
  prefix: /lab

medical_pelanggan:
  resource: 'pelanggan/routing.yml'
  prefix: /pelanggan