AppBundle\Entity\Hasil:
  type: entity
  name: hasil
  repositoryClass: AppBundle\Repository\HasilRepository
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  oneToOne:
    transaksi:
      targetEntity: Transaksi
      inversedBy: hasil
      joinColumn:
        name: transaksi
        referencedColumnName: id
  manyToOne:
    user:
      targetEntity: User
      joinColumn:
        name: user
        referencedColumnName: id
    approvedBy:
      targetEntity: User
      joinColumn:
        name: approved_by
        referencedColumnName: id
  lifecycleCallbacks: {  }
  fields:
    satuan:
      type: string
      length: 100
    parameter:
      type: string
      length: 100
    metodeAnalisa:
      type: string
      length: 255
      name: metode_analisa
    bakuMutu:
      type: string
      length: 255
      name: baku_mutu
    keterangan:
      type: text
      nullable: true
    alasan:
      type: text
      nullable: true
    isApproved:
      type: integer
      nullable: true
  uniqueConstraints:
    event_user_idx:
      columns: transaksi