AppBundle\Entity\Laboratorium:
    type: entity
    table: laboratorium
    repositoryClass: AppBundle\Repository\LaboratoriumRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    oneToMany:
        sampel:
            targetEntity: Sampel
            mappedBy: idLab
            cascade: ["remove"]
    lifecycleCallbacks: {  }
    fields:
      namaLab:
        type: string
        length: 255
      jenisLab:
        type: string
        length: 255
      kodeLab:
        type: string
        length: 100
