AppBundle\Entity\Sampel:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\SampelRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    oneToOne:
      transaksi:
        targetEntity: Transaksi
        mappedBy: sampel
    lifecycleCallbacks: {  }
    manyToOne:
      idLab:
        targetEntity: Laboratorium
        joinColumn:
          name: id_laboratorium
          referencedColumnName: id
    fields:
      lokasiPengambilan:
        type: string
        length: 255
        name: lokasi_pengambilan
      alamat:
        type: string
        length: 255
      petugasPengambil:
        type: string
        length: 255
        name: petugas_pengambil
      tanggal:
        type: datetime
      kondisi:
        type: string
        length: 255
      jenisSampel:
        type: string
        length: 255
        name: jenis_sampel
      parameter:
        type: string
        length: 255
      kodeSampel:
        type: string
        length: 100
        nullable: true
      metodePengambilan:
        type: string
        length: 255
