AppBundle\Entity\Transaksi:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\TransaksiRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    lifecycleCallbacks: {  }
    oneToOne:
      sampel:
        targetEntity: Sampel
        joinColumn:
          name: sampel
          referencedColumnName: id
      hasil:
        targetEntity: Hasil
        mappedBy: transaksi
    manyToOne:
      pelanggan:
        targetEntity: Pelanggan
        joinColumn:
          name: pelanggan
          referencedColumnName: id
    fields:
      biaya:
        type: integer
        length: 100
      tanggalPengambilanHasil:
        type: datetime
        name: tanggal_pengambilan_hasil
