medical_transact_create:
  path: /create
  defaults:
    _controller: AppBundle:Transact/TransactCreate:index

medical_transact_list:
  path: /
  defaults:
    _controller: AppBundle:Transact/TransactList:index

medical_transact_delete:
  path: /delete/{id}
  defaults:
      _controller: AppBundle:Transact/TransactDelete:index
  methods: GET

medical_transact_edit:
  path: /edit/{id}
  defaults:
    _controller: AppBundle:Transact/TransactEdit:index